ci: Ignore misleading indentation as it breaks configure check for flex
Without this, we are getting cryptic configure failures such as

    checking for lex library... not found
    configure: WARNING: required lex library not found; giving up on flex
    AIDE requires GNU flex

and only in the config log finding errors of improperly formatted
conditions:

    lex.yy.c:666:13: error: misleading indentation; statement is not
    part of the previous 'if' [-Werror,-Wmisleading-indentation]
                if ( ! (yy_state_buf) )

Signed-off-by: Jakub Jelen <jjelen@redhat.com>